name: Repo Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  # Paths to exclude from public sync. Relative to repo root.
  # To start syncing a directory with the public repo,
  # remove it from this list and trigger this workflow.
  EXCLUDE_PATHS: |
    content/mongosync/.backportrc.json
    .github/workflows

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Copy To Public
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Remove paths excluded from public sync
      # TODO: set a list of files to remove
        run: |
          git rm -rf $EXCLUDE_PATHS
          git commit -m "Remove paths excluded from public sync"
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Publish Branch
        run: |
          python3 repo_sync.py
        env:
          APP_ID: ${{ vars.APP_ID }}
          INSTALLATION_ID: ${{ vars.INSTALLATION_ID }}
          SERVER_DOCS_PRIVATE_KEY: ${{ secrets.SERVER_DOCS_PRIVATE_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
